server:
    port: 8080
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.16.137:3306/test
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
